### ISSUE TITLE
please solve 

### ISSUE THREAD

**Issue by SIAMRAHMAN1227** [sandrocods/Zefoy-Automation#13]
I DONT USE VPN

![image](https://user-images.githubusercontent.com/117017725/199999469-dfe45659-8b2a-43c5-9a9e-8823a5685bf6.png)

**Comment by sandrocods** [comment]
no error in here 
![image](https://user-images.githubusercontent.com/59155826/200104922-71e8fa4b-e21d-43c4-a541-575032456608.png)
