### ISSUE TITLE
Error Unauthorized 

### ISSUE THREAD

**Issue by anggita13** [sandrocods/Zefoy-Automation#15]
![Screenshot_20221107-203623_NusantaraLauncher~2](https://user-images.githubusercontent.com/86518199/200324833-2c0f67ae-deec-448f-bd84-1a1e6544513b.png)

**Comment by IrishWaffles** [comment]
Zefoy itself seems to be having issues beyond CloudFlare.  Having the same issue myself since last night.

**Comment by sandrocods** [comment]
you can reclone this repository or git pull to update new script
