### ISSUE TITLE
Error Running script

### ISSUE THREAD

**Issue by saabtech** [sandrocods/Zefoy-Automation#19]
The script is not working probably due to the website Cloudfare.

**Comment by Root-FTW** [comment]
Same here

**Comment by sandrocods** [comment]
Cloudflare bypassed ✔
![image](https://user-images.githubusercontent.com/59155826/201468493-c185fbd1-33ed-4c51-bb1c-cba61a212012.png)

**Comment by saabtech** [comment]
> Cloudflare bypassed ✔ ![image](https://user-images.githubusercontent.com/59155826/201468493-c185fbd1-33ed-4c51-bb1c-cba61a212012.png)
> 
> @saabtech , @Root-FTW

Hi , we I am getting this error :
![image](https://user-images.githubusercontent.com/85780689/201470148-dab4088e-058c-4509-86a9-1a6d83a67070.png)

**Comment by sandrocods** [comment]
exe file is no updated

**Comment by saabtech** [comment]
> exe file is no updated

the same happen to the script. see the screenshot below:
![image](https://user-images.githubusercontent.com/85780689/201483900-ec43ab14-17f3-44dc-b4ff-d303f346bf0b.png)

**Comment by sandrocods** [comment]
For cloudflare bypass is not uploaded for now maybe soon i update in github
